apiVersion: v1
kind: ResourceQuota
metadata:
  name: rbe-tenant-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rbe-tenant.labels" . | nindent 4 }}
spec:
  hard:
    pods: {{ .Values.quota.pods | quote }}
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
