apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bb-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rbe-tenant.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "rbe-tenant.scheduler.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
